export const PreviewSection = () => {
  return (
    <section className="py-24 px-6 overflow-hidden relative">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-full max-w-[1000px] h-[500px] bg-emerald-500/5 rounded-full pointer-events-none" />
      
      <div className="max-w-7xl mx-auto relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4">Code Preview Engine</h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            See the exact React and Tailwind code being generated in real-time as you build visually.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-stretch">
          <div className="glass-card rounded-xl p-4 border border-border/50 flex flex-col h-[500px]">
             <div className="border-b border-border/50 pb-4 mb-4 flex items-center justify-between">
               <span className="font-semibold text-sm">Visual Editor</span>
             </div>
             <div className="flex-1 bg-muted/30 rounded-lg flex items-center justify-center border border-dashed border-border/50">
                <button className="px-6 py-3 bg-blue-600 text-white rounded-md shadow-lg shadow-blue-500/20 font-medium">
                  Primary Button
                </button>
             </div>
          </div>
          <div className="glass-card rounded-xl p-4 border border-border/50 flex flex-col h-[500px] bg-zinc-950">
             <div className="border-b border-zinc-800 pb-4 mb-4 flex items-center gap-2">
               <div className="w-3 h-3 rounded-full bg-red-500/50" />
               <div className="w-3 h-3 rounded-full bg-yellow-500/50" />
               <div className="w-3 h-3 rounded-full bg-green-500/50" />
               <span className="ml-4 font-mono text-xs text-zinc-500">Generated Code</span>
             </div>
             <div className="flex-1 overflow-auto">
<pre className="text-sm font-mono text-zinc-300">
<code>{`// Auto-generated by SiteBuilder
import React from 'react';

export default function PrimaryButton() {
  return (
    <button className="
      px-6 py-3 
      bg-blue-600 
      text-white 
      rounded-md 
      shadow-lg 
      shadow-blue-500/20 
      font-medium
      hover:bg-blue-700
      transition-colors
    ">
      Primary Button
    </button>
  );
}
`}</code>
</pre>
             </div>
          </div>
        </div>
      </div>
    </section>
  )
}
